/* Writes src/styles/tokens.css from src/theme.ts — the palette's one copy.
   Runs before dev/check/build (see package.json); the output is generated, so
   it is gitignored and must not be edited by hand.

   Importing a .ts file from a plain node script needs type stripping on by
   default, which is why package.json asks for node >= 22.18.

   Both shells already reduce the reader's choice to `color-scheme`: Starlight
   sets it from [data-theme], the custom pages from [data-mode]. So the tokens
   are emitted once with light-dark(), and a subtree that must stay dark only
   has to declare `color-scheme: dark` — no second copy of the palette. */
import { writeFileSync } from "node:fs";

import { roles, starlight, term } from "../src/theme.ts";

const DARK = 1;
const decl = (name, value) => `  --${name}: ${value};`;
const pair = ([name, [light, dark]]) => decl(name, `light-dark(${light}, ${dark})`);
const darkOnly = ([name, values]) => decl(name, values[DARK]);

const out = `/* Generated by scripts/build-tokens.mjs from src/theme.ts — do not edit. */

/* Starlight ships its own props inside @layer starlight.base, and customCss is
   imported unlayered — an unlayered declaration wins over any layered one, so
   a bare :root is enough to override them. */
:root {
${Object.entries(roles).map(pair).join("\n")}

  /* The terminal panes: Mocha in both modes, so no light-dark() here. Any
     element painted with --term-bg also sets color-scheme: dark, which is what
     makes the roles above resolve to their Mocha side inside it. */
${Object.entries(term)
  .map(([name, value]) => decl(`term-${name}`, value))
  .join("\n")}

  /* Starlight's tokens. Nothing in this repo reads them; the docs shell does. */
${Object.entries(starlight)
  .map(([name, values]) => pair([`sl-${name}`, values]))
  .join("\n")}
}

/* A browser without light-dark() would drop every declaration above and paint
   an unstyled page. Give it the dark side, which is the site's default mode.
   (Baseline: Chrome 123, Safari 17.5, Firefox 120 — all 2024.) */
@supports not (color: light-dark(#000, #fff)) {
  :root {
${Object.entries(roles).map(darkOnly).join("\n")}
${Object.entries(starlight)
  .map(([name, values]) => darkOnly([`sl-${name}`, values]))
  .join("\n")}
  }
}
`;

const target = new URL("../src/styles/tokens.css", import.meta.url);
writeFileSync(target, out);
console.log(`tokens: ${Object.keys(roles).length} roles, ${Object.keys(term).length} terminal,` +
  ` ${Object.keys(starlight).length} starlight`);
